import type { Reservoir } from "@/lib/fishing-types";

export const reservoirs: Reservoir[] = [
  {
    id: "garcia-sola",
    name: "García Sola",
    province: "Badajoz",
    basin: "Guadiana",
    latitude: 39.5625,
    longitude: -5.0625,
    primarySpecies: ["black bass", "lucio", "barbo", "lucioperca"],
    forage: ["alburno", "cangrejo", "percasol"],
    pressure: "alta",
    clarity: "clara",
    notes: "Embalse presionado pero con pez de calidad, algueros importantes y lectura táctica muy dependiente de viento, cobertura y transición.",
    publicZones: ["Puente de Castilblanco", "reculas", "puntas con acceso a canal", "riprap y piedra"],
    privateSupport: true,
  },
  {
    id: "cijara",
    name: "Cíjara",
    province: "Badajoz/Ciudad Real",
    basin: "Guadiana",
    latitude: 39.204,
    longitude: -4.857,
    primarySpecies: ["black bass", "lucio", "barbo", "lucioperca"],
    forage: ["alburno", "cangrejo"],
    pressure: "media",
    clarity: "mixta",
    notes: "Gran extensión, mucha agua para leer bien y potencial serio para bass y lucio.",
    publicZones: ["colas", "brazos remotos", "recortados rocosos"],
    privateSupport: true,
  },
  {
    id: "orellana",
    name: "Orellana",
    province: "Badajoz",
    basin: "Guadiana",
    latitude: 39.021,
    longitude: -5.534,
    primarySpecies: ["black bass", "lucio", "barbo"],
    forage: ["alburno", "cangrejo"],
    pressure: "alta",
    clarity: "clara",
    notes: "Agua clara, pez receloso y mucha importancia de la lectura fina de estructura y profundidad.",
    publicZones: ["playas técnicas", "puntas", "cambios de piedra"],
    privateSupport: true,
  },
  {
    id: "la-fernandina",
    name: "La Fernandina",
    province: "Jaén/Ciudad Real",
    basin: "Guadalquivir",
    latitude: 38.391,
    longitude: -3.474,
    primarySpecies: ["black bass", "lucio", "barbo"],
    forage: ["pez pasto local", "cangrejo"],
    pressure: "media",
    clarity: "mixta",
    notes: "Embalse a perfilar con detalle en la base de conocimiento inicial.",
    publicZones: ["reculas", "orillas mixtas"],
    privateSupport: true,
  },
  {
    id: "encinarejo",
    name: "Encinarejo",
    province: "Jaén",
    basin: "Guadalquivir",
    latitude: 38.015,
    longitude: -4.347,
    primarySpecies: ["black bass", "lucio", "barbo"],
    forage: ["pez pasto local", "cangrejo"],
    pressure: "media",
    clarity: "mixta",
    notes: "Muy relevante para lectura de coberturas, vegetación y patrones de primavera.",
    publicZones: ["vegetación", "orillas someras", "entradas de agua"],
    privateSupport: true,
  },
  {
    id: "guadalmena",
    name: "Guadalmena",
    province: "Jaén/Albacete",
    basin: "Guadalquivir",
    latitude: 38.459,
    longitude: -2.626,
    primarySpecies: ["black bass", "lucio", "barbo"],
    forage: ["pez pasto local", "cangrejo"],
    pressure: "media",
    clarity: "mixta",
    notes: "Embalse de alto interés para depredadores, a documentar con spots y época.",
    publicZones: ["cortados", "puntas", "brazos"],
    privateSupport: true,
  },
  {
    id: "yeguas",
    name: "Yeguas",
    province: "Córdoba/Jaén",
    basin: "Guadalquivir",
    latitude: 38.072,
    longitude: -4.492,
    primarySpecies: ["black bass", "lucio", "barbo"],
    forage: ["pez pasto local", "cangrejo"],
    pressure: "media",
    clarity: "mixta",
    notes: "Interesante para jornadas técnicas y lectura de agua por sectores.",
    publicZones: ["puntas", "orillas tomadas", "transiciones"],
    privateSupport: true,
  },
  {
    id: "san-rafael-de-navallana",
    name: "San Rafael de Navallana",
    province: "Córdoba",
    basin: "Guadalquivir",
    latitude: 37.988,
    longitude: -4.479,
    primarySpecies: ["black bass", "lucio", "barbo"],
    forage: ["pez pasto local", "cangrejo"],
    pressure: "alta",
    clarity: "mixta",
    notes: "Muy útil contemplar presión, orillas accesibles y lectura de actividad por viento.",
    publicZones: ["orillas someras", "estructuras", "colas"],
    privateSupport: true,
  },
  {
    id: "la-brena",
    name: "La Breña",
    province: "Córdoba",
    basin: "Guadalquivir",
    latitude: 37.85,
    longitude: -5.02,
    primarySpecies: ["black bass", "barbo"],
    forage: ["pez pasto local", "cangrejo"],
    pressure: "media",
    clarity: "mixta",
    notes: "Embalse a modelar con detalle específico por estaciones y nivel.",
    publicZones: ["paredes", "reculas", "zonas mixtas"],
    privateSupport: true,
  },
];

export const reservoirLevelSources: Record<string, string> = {
  "garcia-sola": "https://embalses.info/embalse/garcia-de-sola",
  cijara: "https://embalses.info/embalse/cijara",
  orellana: "https://embalses.info/embalse/orellana",
};

export const appRoadmap = [
  "Live weather, wind and solunar ingestion",
  "Reservoir level trend connectors",
  "Private spots with aliases, notes and sensitivity controls",
  "Sonar mode with Eagle Eye / Damiki decision hints",
  "Session logs and learning loop",
];

export const privateSpotModel = {
  aliasVisible: "Castillo Norte 2",
  coordinatesStored: true,
  coordinatesExposedInUi: false,
  sensitivity: "private",
};
